[
    {
        "id": "6658741598",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2020770015,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "1454b417c9461a428466e73b9278e1627d0f29b3",
            "before": "2db50f0a34e5b8264724c658b1fa9e7fb19aa746",
            "commits": [
                {
                    "sha": "1454b417c9461a428466e73b9278e1627d0f29b3",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "removed masking again favicon broke",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/1454b417c9461a428466e73b9278e1627d0f29b3"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T23:29:42Z"
    },
    {
        "id": "6658735259",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2020765989,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "2db50f0a34e5b8264724c658b1fa9e7fb19aa746",
            "before": "449d1ef679a48c7787adf1e48a74c5b4bc11b9a6",
            "commits": [
                {
                    "sha": "2db50f0a34e5b8264724c658b1fa9e7fb19aa746",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "corrected some grammar errors, corrected right margin on tech skills, and re arranged portfolio again",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/2db50f0a34e5b8264724c658b1fa9e7fb19aa746"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T23:23:23Z"
    },
    {
        "id": "6658728914",
        "type": "IssuesEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/25",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/25/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/25/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/25/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/25",
                "id": 260947958,
                "number": 25,
                "title": "favicon does not display when deployed",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2017-09-27T12:00:37Z",
                "updated_at": "2017-09-30T23:17:27Z",
                "closed_at": "2017-09-30T23:17:27Z",
                "author_association": "OWNER",
                "body": ""
            }
        },
        "public": true,
        "created_at": "2017-09-30T23:17:27Z"
    },
    {
        "id": "6658728762",
        "type": "IssuesEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/31",
                "id": 261760685,
                "number": 31,
                "title": "Objective text",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2017-09-29T20:24:09Z",
                "updated_at": "2017-09-30T23:17:18Z",
                "closed_at": "2017-09-30T23:17:18Z",
                "author_association": "OWNER",
                "body": "Covered by fixed links in some views needs a harder right margin"
            }
        },
        "public": true,
        "created_at": "2017-09-30T23:17:18Z"
    },
    {
        "id": "6658728760",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/31",
                "id": 261760685,
                "number": 31,
                "title": "Objective text",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2017-09-29T20:24:09Z",
                "updated_at": "2017-09-30T23:17:18Z",
                "closed_at": "2017-09-30T23:17:18Z",
                "author_association": "OWNER",
                "body": "Covered by fixed links in some views needs a harder right margin"
            },
            "comment": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/comments/333342424",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/31#issuecomment-333342424",
                "issue_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31",
                "id": 333342424,
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2017-09-30T23:17:18Z",
                "updated_at": "2017-09-30T23:17:18Z",
                "author_association": "OWNER",
                "body": "corrected"
            }
        },
        "public": true,
        "created_at": "2017-09-30T23:17:18Z"
    },
    {
        "id": "6658331092",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2020518087,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "449d1ef679a48c7787adf1e48a74c5b4bc11b9a6",
            "before": "302483a3bb08675c2a493a6c2c7d01d88b7594de",
            "commits": [
                {
                    "sha": "449d1ef679a48c7787adf1e48a74c5b4bc11b9a6",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "Updated portfolio",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/449d1ef679a48c7787adf1e48a74c5b4bc11b9a6"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T17:55:53Z"
    },
    {
        "id": "6658298487",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 105387381,
            "name": "901david/utileDevelopersApplication",
            "url": "https://api.github.com/repos/901david/utileDevelopersApplication"
        },
        "payload": {
            "push_id": 2020498524,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "ba0174b48c5c25194eec3b0845a22c58f4c78594",
            "before": "57a5019d3c8dd61cebe1cf6fb3c2d1a1489254f3",
            "commits": [
                {
                    "sha": "ba0174b48c5c25194eec3b0845a22c58f4c78594",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "901david"
                    },
                    "message": "updated read me",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/utileDevelopersApplication/commits/ba0174b48c5c25194eec3b0845a22c58f4c78594"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T17:31:59Z"
    },
    {
        "id": "6658292319",
        "type": "CreateEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 105387381,
            "name": "901david/utileDevelopersApplication",
            "url": "https://api.github.com/repos/901david/utileDevelopersApplication"
        },
        "payload": {
            "ref": "master",
            "ref_type": "branch",
            "master_branch": "master",
            "description": "An application that allows developers to develop in more efficient and collaborative manner",
            "pusher_type": "user"
        },
        "public": true,
        "created_at": "2017-09-30T17:27:19Z"
    },
    {
        "id": "6658292296",
        "type": "CreateEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 105387381,
            "name": "901david/utileDevelopersApplication",
            "url": "https://api.github.com/repos/901david/utileDevelopersApplication"
        },
        "payload": {
            "ref": null,
            "ref_type": "repository",
            "master_branch": "master",
            "description": "An application that allows developers to develop in more efficient and collaborative manner",
            "pusher_type": "user"
        },
        "public": true,
        "created_at": "2017-09-30T17:27:18Z"
    },
    {
        "id": "6658179827",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2020426957,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "302483a3bb08675c2a493a6c2c7d01d88b7594de",
            "before": "62cc9b1035bcd9881500cc485da24a192ddfb1db",
            "commits": [
                {
                    "sha": "302483a3bb08675c2a493a6c2c7d01d88b7594de",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "uncommented mailgun",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/302483a3bb08675c2a493a6c2c7d01d88b7594de"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T16:05:19Z"
    },
    {
        "id": "6657355191",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 104589825,
            "name": "901david/uTileDevelopersSiteV1",
            "url": "https://api.github.com/repos/901david/uTileDevelopersSiteV1"
        },
        "payload": {
            "push_id": 2019932888,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "1e8a160d36f0513ca6f6a69af3ead853c4a70e51",
            "before": "b6c176cdfa5d36f7a0de7d496742c006335823d4",
            "commits": [
                {
                    "sha": "1e8a160d36f0513ca6f6a69af3ead853c4a70e51",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "David Hammond"
                    },
                    "message": "Update README.md",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/uTileDevelopersSiteV1/commits/1e8a160d36f0513ca6f6a69af3ead853c4a70e51"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T04:07:33Z"
    },
    {
        "id": "6657287516",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019893357,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "62cc9b1035bcd9881500cc485da24a192ddfb1db",
            "before": "b5ec066e99a181f694520d380aa6d7dda97424f2",
            "commits": [
                {
                    "sha": "62cc9b1035bcd9881500cc485da24a192ddfb1db",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "now switching it to the masked url",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/62cc9b1035bcd9881500cc485da24a192ddfb1db"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T03:10:11Z"
    },
    {
        "id": "6657284401",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019891509,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "b5ec066e99a181f694520d380aa6d7dda97424f2",
            "before": "8aa72df612d55377bb1014da6b02f97d5abc4e1f",
            "commits": [
                {
                    "sha": "b5ec066e99a181f694520d380aa6d7dda97424f2",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "changed favicon to a direct link that is erving appropriately",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/b5ec066e99a181f694520d380aa6d7dda97424f2"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T03:07:43Z"
    },
    {
        "id": "6657278738",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019888221,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "8aa72df612d55377bb1014da6b02f97d5abc4e1f",
            "before": "ecaf754b58f821dd614811711a06247f9d5d1757",
            "commits": [
                {
                    "sha": "8aa72df612d55377bb1014da6b02f97d5abc4e1f",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "removed serve favicon",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/8aa72df612d55377bb1014da6b02f97d5abc4e1f"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T03:03:08Z"
    },
    {
        "id": "6657262404",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019878971,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "ecaf754b58f821dd614811711a06247f9d5d1757",
            "before": "3f2a84b054bb64b996d650bc008a08ccbc52fa20",
            "commits": [
                {
                    "sha": "ecaf754b58f821dd614811711a06247f9d5d1757",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "converted back to ico file",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/ecaf754b58f821dd614811711a06247f9d5d1757"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T02:50:38Z"
    },
    {
        "id": "6657251421",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019872532,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "3f2a84b054bb64b996d650bc008a08ccbc52fa20",
            "before": "4ac1721d2be909a7fdd7867fcb4b2c1a8e8a2949",
            "commits": [
                {
                    "sha": "3f2a84b054bb64b996d650bc008a08ccbc52fa20",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "re-integrated in serve-favicon",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/3f2a84b054bb64b996d650bc008a08ccbc52fa20"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-30T02:42:17Z"
    },
    {
        "id": "6656647774",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019541441,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "4ac1721d2be909a7fdd7867fcb4b2c1a8e8a2949",
            "before": "4d4563f7446485c0caff647c515f49a500a87370",
            "commits": [
                {
                    "sha": "4ac1721d2be909a7fdd7867fcb4b2c1a8e8a2949",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "changing wrong margin, corrected now",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/4ac1721d2be909a7fdd7867fcb4b2c1a8e8a2949"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-29T21:33:27Z"
    },
    {
        "id": "6656628962",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019531511,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "4d4563f7446485c0caff647c515f49a500a87370",
            "before": "b92a5325c048054166b2edba510b6535a9aac5c5",
            "commits": [
                {
                    "sha": "4d4563f7446485c0caff647c515f49a500a87370",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "75px left margin just was not enough increased to 85px",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/4d4563f7446485c0caff647c515f49a500a87370"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-29T21:27:56Z"
    },
    {
        "id": "6656578309",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019505658,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "b92a5325c048054166b2edba510b6535a9aac5c5",
            "before": "8d978b647a0eac5828693e86ee86d0fb77b8b368",
            "commits": [
                {
                    "sha": "b92a5325c048054166b2edba510b6535a9aac5c5",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "corrected objective margin in LG mode, was covered by nav bar added in another 25pc margin left",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/b92a5325c048054166b2edba510b6535a9aac5c5"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-29T21:13:19Z"
    },
    {
        "id": "6656429214",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019428711,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "8d978b647a0eac5828693e86ee86d0fb77b8b368",
            "before": "8d95bb328c07a5ca75f821729d836b2c7cb5a393",
            "commits": [
                {
                    "sha": "8d978b647a0eac5828693e86ee86d0fb77b8b368",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "New build",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/8d978b647a0eac5828693e86ee86d0fb77b8b368"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-29T20:33:47Z"
    },
    {
        "id": "6656425856",
        "type": "PushEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "push_id": 2019426940,
            "size": 1,
            "distinct_size": 1,
            "ref": "refs/heads/master",
            "head": "8d95bb328c07a5ca75f821729d836b2c7cb5a393",
            "before": "6c703eebdea3755e26ca6fb62fd3b2861a5bdbde",
            "commits": [
                {
                    "sha": "8d95bb328c07a5ca75f821729d836b2c7cb5a393",
                    "author": {
                        "email": "vdavidhammond@gmail.com",
                        "name": "DHLAP\\h"
                    },
                    "message": "Corrected nav height in lower resolution mobile views",
                    "distinct": true,
                    "url": "https://api.github.com/repos/901david/portfolio_dh_react/commits/8d95bb328c07a5ca75f821729d836b2c7cb5a393"
                }
            ]
        },
        "public": true,
        "created_at": "2017-09-29T20:32:54Z"
    },
    {
        "id": "6656391070",
        "type": "IssuesEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "opened",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/31/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/31",
                "id": 261760685,
                "number": 31,
                "title": "Objective text",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2017-09-29T20:24:09Z",
                "updated_at": "2017-09-29T20:24:09Z",
                "closed_at": null,
                "author_association": "OWNER",
                "body": "Covered by fixed links in some views needs a harder right margin"
            }
        },
        "public": true,
        "created_at": "2017-09-29T20:24:10Z"
    },
    {
        "id": "6656388222",
        "type": "IssuesEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/23",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/23/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/23/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/23/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/23",
                "id": 258275377,
                "number": 23,
                "title": "Iphone 7 - nav bar height",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2017-09-17T03:23:13Z",
                "updated_at": "2017-09-29T20:23:26Z",
                "closed_at": "2017-09-29T20:23:26Z",
                "author_association": "OWNER",
                "body": ""
            }
        },
        "public": true,
        "created_at": "2017-09-29T20:23:26Z"
    },
    {
        "id": "6656388216",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/23",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/23/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/23/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/23/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/23",
                "id": 258275377,
                "number": 23,
                "title": "Iphone 7 - nav bar height",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2017-09-17T03:23:13Z",
                "updated_at": "2017-09-29T20:23:26Z",
                "closed_at": "2017-09-29T20:23:26Z",
                "author_association": "OWNER",
                "body": ""
            },
            "comment": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/comments/333229818",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/23#issuecomment-333229818",
                "issue_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/23",
                "id": 333229818,
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2017-09-29T20:23:26Z",
                "updated_at": "2017-09-29T20:23:26Z",
                "author_association": "OWNER",
                "body": "Corrected"
            }
        },
        "public": true,
        "created_at": "2017-09-29T20:23:26Z"
    },
    {
        "id": "6656387604",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/22",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/22/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/22/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/22/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/22",
                "id": 258275317,
                "number": 22,
                "title": "Nexus 6P",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2017-09-17T03:21:56Z",
                "updated_at": "2017-09-29T20:23:17Z",
                "closed_at": "2017-09-29T20:23:17Z",
                "author_association": "OWNER",
                "body": "Nav bar needs height larger"
            },
            "comment": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/comments/333229786",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/22#issuecomment-333229786",
                "issue_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/22",
                "id": 333229786,
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2017-09-29T20:23:17Z",
                "updated_at": "2017-09-29T20:23:17Z",
                "author_association": "OWNER",
                "body": "Corrected"
            }
        },
        "public": true,
        "created_at": "2017-09-29T20:23:17Z"
    },
    {
        "id": "6656386873",
        "type": "IssuesEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/21",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/21/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/21/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/21/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/21",
                "id": 258275285,
                "number": 21,
                "title": "Mobile Responsive - ipad air",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2017-09-17T03:20:55Z",
                "updated_at": "2017-09-29T20:23:06Z",
                "closed_at": "2017-09-29T20:23:06Z",
                "author_association": "OWNER",
                "body": "* projects look weird in this view, need to be moved over"
            }
        },
        "public": true,
        "created_at": "2017-09-29T20:23:07Z"
    },
    {
        "id": "6656386850",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/21",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/21/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/21/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/21/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/21",
                "id": 258275285,
                "number": 21,
                "title": "Mobile Responsive - ipad air",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2017-09-17T03:20:55Z",
                "updated_at": "2017-09-29T20:23:06Z",
                "closed_at": "2017-09-29T20:23:06Z",
                "author_association": "OWNER",
                "body": "* projects look weird in this view, need to be moved over"
            },
            "comment": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/comments/333229750",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/21#issuecomment-333229750",
                "issue_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/21",
                "id": 333229750,
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2017-09-29T20:23:06Z",
                "updated_at": "2017-09-29T20:23:06Z",
                "author_association": "OWNER",
                "body": "Corrected"
            }
        },
        "public": true,
        "created_at": "2017-09-29T20:23:06Z"
    },
    {
        "id": "6656383315",
        "type": "IssuesEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/24",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/24/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/24/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/24/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/24",
                "id": 258275390,
                "number": 24,
                "title": "Iphone 6 - Nav bar height",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2017-09-17T03:23:28Z",
                "updated_at": "2017-09-29T20:22:13Z",
                "closed_at": "2017-09-29T20:22:13Z",
                "author_association": "OWNER",
                "body": ""
            }
        },
        "public": true,
        "created_at": "2017-09-29T20:22:13Z"
    },
    {
        "id": "6656383300",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/24",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/24/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/24/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/24/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/24",
                "id": 258275390,
                "number": 24,
                "title": "Iphone 6 - Nav bar height",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2017-09-17T03:23:28Z",
                "updated_at": "2017-09-29T20:22:13Z",
                "closed_at": "2017-09-29T20:22:13Z",
                "author_association": "OWNER",
                "body": ""
            },
            "comment": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/comments/333229530",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/24#issuecomment-333229530",
                "issue_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/24",
                "id": 333229530,
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2017-09-29T20:22:12Z",
                "updated_at": "2017-09-29T20:22:12Z",
                "author_association": "OWNER",
                "body": "Corrected"
            }
        },
        "public": true,
        "created_at": "2017-09-29T20:22:13Z"
    },
    {
        "id": "6656239292",
        "type": "IssuesEvent",
        "actor": {
            "id": 26396882,
            "login": "901david",
            "display_login": "901david",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "avatar_url": "https://avatars.githubusercontent.com/u/26396882?"
        },
        "repo": {
            "id": 102167284,
            "name": "901david/portfolio_dh_react",
            "url": "https://api.github.com/repos/901david/portfolio_dh_react"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/29",
                "repository_url": "https://api.github.com/repos/901david/portfolio_dh_react",
                "labels_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/29/labels{/name}",
                "comments_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/29/comments",
                "events_url": "https://api.github.com/repos/901david/portfolio_dh_react/issues/29/events",
                "html_url": "https://github.com/901david/portfolio_dh_react/issues/29",
                "id": 260948170,
                "number": 29,
                "title": "make portfolio match margins of rest of page...",
                "user": {
                    "login": "901david",
                    "id": 26396882,
                    "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/901david",
                    "html_url": "https://github.com/901david",
                    "followers_url": "https://api.github.com/users/901david/followers",
                    "following_url": "https://api.github.com/users/901david/following{/other_user}",
                    "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
                    "organizations_url": "https://api.github.com/users/901david/orgs",
                    "repos_url": "https://api.github.com/users/901david/repos",
                    "events_url": "https://api.github.com/users/901david/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/901david/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2017-09-27T12:01:24Z",
                "updated_at": "2017-09-29T19:44:36Z",
                "closed_at": "2017-09-29T19:44:36Z",
                "author_association": "OWNER",
                "body": ""
            }
        },
        "public": true,
        "created_at": "2017-09-29T19:44:37Z"
    }
]
