[
    {
        "login": "Elektro1776",
        "id": 16568965,
        "avatar_url": "https://avatars1.githubusercontent.com/u/16568965?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Elektro1776",
        "html_url": "https://github.com/Elektro1776",
        "followers_url": "https://api.github.com/users/Elektro1776/followers",
        "following_url": "https://api.github.com/users/Elektro1776/following{/other_user}",
        "gists_url": "https://api.github.com/users/Elektro1776/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Elektro1776/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Elektro1776/subscriptions",
        "organizations_url": "https://api.github.com/users/Elektro1776/orgs",
        "repos_url": "https://api.github.com/users/Elektro1776/repos",
        "events_url": "https://api.github.com/users/Elektro1776/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Elektro1776/received_events",
        "type": "User",
        "site_admin": false,
        "permissions": {
            "admin": true,
            "push": true,
            "pull": true
        }
    },
    {
        "login": "cemitchell25",
        "id": 22401442,
        "avatar_url": "https://avatars3.githubusercontent.com/u/22401442?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cemitchell25",
        "html_url": "https://github.com/cemitchell25",
        "followers_url": "https://api.github.com/users/cemitchell25/followers",
        "following_url": "https://api.github.com/users/cemitchell25/following{/other_user}",
        "gists_url": "https://api.github.com/users/cemitchell25/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cemitchell25/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cemitchell25/subscriptions",
        "organizations_url": "https://api.github.com/users/cemitchell25/orgs",
        "repos_url": "https://api.github.com/users/cemitchell25/repos",
        "events_url": "https://api.github.com/users/cemitchell25/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cemitchell25/received_events",
        "type": "User",
        "site_admin": false,
        "permissions": {
            "admin": false,
            "push": true,
            "pull": true
        }
    },
    {
        "login": "Soup-Flies",
        "id": 25832401,
        "avatar_url": "https://avatars2.githubusercontent.com/u/25832401?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Soup-Flies",
        "html_url": "https://github.com/Soup-Flies",
        "followers_url": "https://api.github.com/users/Soup-Flies/followers",
        "following_url": "https://api.github.com/users/Soup-Flies/following{/other_user}",
        "gists_url": "https://api.github.com/users/Soup-Flies/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Soup-Flies/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Soup-Flies/subscriptions",
        "organizations_url": "https://api.github.com/users/Soup-Flies/orgs",
        "repos_url": "https://api.github.com/users/Soup-Flies/repos",
        "events_url": "https://api.github.com/users/Soup-Flies/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Soup-Flies/received_events",
        "type": "User",
        "site_admin": false,
        "permissions": {
            "admin": false,
            "push": true,
            "pull": true
        }
    },
    {
        "login": "901david",
        "id": 26396882,
        "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/901david",
        "html_url": "https://github.com/901david",
        "followers_url": "https://api.github.com/users/901david/followers",
        "following_url": "https://api.github.com/users/901david/following{/other_user}",
        "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
        "organizations_url": "https://api.github.com/users/901david/orgs",
        "repos_url": "https://api.github.com/users/901david/repos",
        "events_url": "https://api.github.com/users/901david/events{/privacy}",
        "received_events_url": "https://api.github.com/users/901david/received_events",
        "type": "User",
        "site_admin": false,
        "permissions": {
            "admin": false,
            "push": true,
            "pull": true
        }
    }
]
