const commentData = [
    {
        "url": "https://api.github.com/repos/901david/Flashcard-Fun/issues/comments/324126027",
        "html_url": "https://github.com/901david/Flashcard-Fun/issues/25#issuecomment-324126027",
        "issue_url": "https://api.github.com/repos/901david/Flashcard-Fun/issues/25",
        "id": 324126027,
        "user": {
            "login": "901david",
            "id": 26396882,
            "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "html_url": "https://github.com/901david",
            "followers_url": "https://api.github.com/users/901david/followers",
            "following_url": "https://api.github.com/users/901david/following{/other_user}",
            "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
            "organizations_url": "https://api.github.com/users/901david/orgs",
            "repos_url": "https://api.github.com/users/901david/repos",
            "events_url": "https://api.github.com/users/901david/events{/privacy}",
            "received_events_url": "https://api.github.com/users/901david/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2017-08-22T19:21:35Z",
        "updated_at": "2017-08-22T19:21:35Z",
        "author_association": "OWNER",
        "body": "This comment was created by Postman - pretty F'in Cool"
    },
    {
        "url": "https://api.github.com/repos/901david/Flashcard-Fun/issues/comments/324190860",
        "html_url": "https://github.com/901david/Flashcard-Fun/issues/25#issuecomment-324190860",
        "issue_url": "https://api.github.com/repos/901david/Flashcard-Fun/issues/25",
        "id": 324190860,
        "user": {
            "login": "901david",
            "id": 26396882,
            "avatar_url": "https://avatars1.githubusercontent.com/u/26396882?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/901david",
            "html_url": "https://github.com/901david",
            "followers_url": "https://api.github.com/users/901david/followers",
            "following_url": "https://api.github.com/users/901david/following{/other_user}",
            "gists_url": "https://api.github.com/users/901david/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/901david/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/901david/subscriptions",
            "organizations_url": "https://api.github.com/users/901david/orgs",
            "repos_url": "https://api.github.com/users/901david/repos",
            "events_url": "https://api.github.com/users/901david/events{/privacy}",
            "received_events_url": "https://api.github.com/users/901david/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2017-08-23T00:54:48Z",
        "updated_at": "2017-08-23T00:55:49Z",
        "author_association": "OWNER",
        "body": "Look I just changed this"
    }
];
export default commentData;
