/**
ISSUES FROM GITHUB => CREATE USER STORIES FROM ISSUES => SUBTASKS CREATED IN USERSTORIES

ISSUES CAN BE CREATED AND PUSHED TO github

USERSTORIES ARE SOLEY CREATED ON OUR APPLICATION FROM ISSUES WHICH CAN THEN
BE BROKEN DOWN INTO SUBTASKS TO ACCOMPLISH USERSTORIES WHICH IN TURN WILL
COMPLETE THE ISSUE

NICE TO HAVE : ALLOW FOR PR CREATION WITH  `closes issues #28` to allow for auto closing
of issues that have been given a user story on our end

*/
